routes/web.php
<?php


use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\EventController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\Public\SectionController as PublicSection;
use App\Http\Controllers\Public\ArticleController as PublicArticle;
use App\Http\Controllers\Public\EventController as PublicEvent;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => '/'], function() {
    Route::get('', [MainController::class, 'index'])->name('index');

    Route::get('authorize', [AuthController::class, 'showAuth'])->name('authorize');
    Route::post('authorize', [AuthController::class, 'auth'])->name('authorize.post');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    Route::group(['prefix' => 'section'], function() {
//        FIXME: подумать ещё раз над URL
        Route::get('{sectionAlias}/{subsectionAlias}/articles/{articleAlias}', [PublicArticle::class, 'getSubsectionArticle'])->name('get-subsection-article');
        Route::get('{sectionAlias}/articles/{articleAlias}', [PublicArticle::class, 'getSectionArticle'])->name('get-section-article');
        Route::get('{sectionAlias}/{subsectionAlias}', [PublicSection::class, 'getSubsection'])->name('get-subsection');
        Route::get('{sectionAlias}', [PublicSection::class, 'getSection'])->name('get-section');
    });

    Route::group(['prefix' => 'events'], function() {
        Route::get('today', [PublicEvent::class, 'getTodayEvents'])->name('today-events');
        Route::get('coming-soon', [PublicEvent::class, 'getComingSoonEvents'])->name('coming-son-events');
        Route::get('off-site', [PublicEvent::class, 'getOffsiteEvents'])->name('off-site-events');
    });

    Route::group(['prefix' => 'admin', 'middleware' => 'role'], function() {
        Route::get('', [AdminController::class, 'index'])->name('admin-dashboard');
        Route::resource('users', UserController::class);
        Route::resource('partners', PartnerController::class);
        Route::resource('banners', BannerController::class);
        Route::resource('sections', SectionController::class);
        Route::resource('articles', ArticleController::class);
        Route::resource('events', EventController::class);
        Route::get('images', [ImageController::class, 'getImages'])->name('images');
        Route::post('images/{image}', [ImageController::class, 'deleteImage'])->name('delete-image');
        Route::get('images/{id}/update', [ImageController::class, 'getEditImage'])->name('update-image');
        Route::post('images/{id}/update', [ImageController::class, 'editImage'])->name('update-image-post');
        Route::post('images/store', [ImageController::class, 'store'])->name('images.store');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function checkRole() {
        if (Auth::check()) {
            return match (Auth::user()->role) {
                'moderator', 'admin' => true,
                default => false,
            };
        }
        return false;
    }

    public function isAdmin(): bool {
        if (Auth::check()) {
            if (Auth::user()->role === 'admin') return true;
        }
        return false;
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\CreateUserRequestController;
use App\Http\Requests\User\UpdateUserRequestController;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    private $sorting;

    public function __construct() {
        $this->sorting = [
            'asc' => ['id', 'asc'],
            'desc' => ['id', 'desc']
        ];
    }

    public function index(Request $request)
    {
        $params = $request->validate([
            'search' => 'sometimes',
            'sort' => 'sometimes'
        ]);

        $users = User::query()->where('role', 'moderator');

        if (isset($params['search']) && !empty($params['search'])) {
            $users = $users->where(function ($query) use ($params) {
                $query->where('email', 'like', '%' . $params['search'] . '%')
                    ->orWhere('login', 'like', '%' . $params['search'] . '%');
            });
        }

        if (isset($params['sort']) && !empty($params['sort'])) {
            $currentParams = $this->sorting[$params['sort']];
            $users = $users->orderBy($currentParams[0], $currentParams[1]);
        }

        $users = $users->get();

        return view('admin_layouts.user.users', [
            'users' => $users
        ]);
    }


    public function create()
    {
        return view('admin_layouts.user.create_user');
    }


    public function store(CreateUserRequestController $request)
    {
        $post = $request->validated();

        $user = new User();
        $user->email = $post['email'];
        $user->login = $post['login'];
        $user->role = $post['role'];
        $user->password = Hash::make($post['password']);
        $user->save();

        return redirect()->route('users.index');
    }

    public function edit(User $user)
    {
        $userEdit = User::findOrFail($user->id);

        return view('admin_layouts.user.edit_user', [
            'user' => $userEdit
        ]);
    }

    public function update(UpdateUserRequestController $request, User $user)
    {
        $post = $request->validated();

        $updateUser = User::findOrFail($user->id);
        $updateUser->email = $post['email'];
        $updateUser->login = $post['login'];
        $updateUser->role = $post['role'];
        $updateUser->save();

        return redirect()->route('users.index');
    }

    public function destroy(User $user)
    {
        $deleteUser = User::findOrFail($user->id);
        $deleteUser->delete();

        return redirect()->route('users.index');
    }
}

resources/views/admin_layouts/user/create_user.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Создание пользователя</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="centered-page">
        <form class="centered-form p-4 sm:p-8" action="{{ route('users.store') }}" method="post" enctype="multipart/form-data">
            <header class="grid gap-2">
                <a class="link flex gap-1" href="{{ route('users.index') }}">
                    @include('layouts.svg.left-arrow')
                    Назад
                </a>
                <h1 class="text-2xl sm:text-4xl text-center">Создание пользователя</h1>
                <span class="line"></span>
            </header>
            @if ($errors->any())
                <div class="bg-red-500 border border-red-600 p-1 rounded text-white">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @csrf
            <f-field class="grid gap-1">
                <label for="email">E-mail</label>
                <input class="input" type="text" name="email" id="email" value="{{ old('email') }}" placeholder="Почта">
            </f-field>
            <f-field class="grid gap-1">
                <label for="login">Логин</label>
                <input class="input" type="text" name="login" id="login" value="{{ old('login') }}" placeholder="Логин">
            </f-field>
            <f-field class="grid gap-1">
                <label for="role">Роль</label>
                <select name="role" id="role">
                    <option value="null">Выберите роль</option>
                    <option value="moderator">Модератор</option>
                </select>
            </f-field>
            <f-field class="grid gap-1">
                <label for="password">Пароль</label>
                <input class="input" type="password" name="password" id="password" placeholder="Пароль">
            </f-field>
            <f-field class="grid gap-1">
                <label for="password_confirm">Повторите пароль</label>
                <input class="input" type="password" name="password_confirmation" id="password_confirm" placeholder="Повторите пароль">
            </f-field>
            <button class="btn btn-accent">Создать</button>
        </form>
    </body>
</html>

resources/views/admin_layouts/user/edit_user.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Изменение пользователя</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="centered-page">
        <form class="centered-form p-4 sm:p-8" action="{{ route('users.update', ['user' => $user]) }}" method="post">
            <header class="grid gap-2">
                <a class="link flex gap-1" href="{{ route('users.index') }}">
                    @include('layouts.svg.left-arrow')
                    Назад
                </a>
                <h1 class="text-2xl sm:text-4xl text-center">Изменение пользователя</h1>
                <span class="line"></span>
            </header>
            @if ($errors->any())
                <div class="bg-red-500 border border-red-600 p-1 rounded text-white">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @csrf
            @method('PUT')
            <f-field class="grid gap-1">
                <label for="email">E-mail</label>
                <input class="input" type="text" name="email" id="email" value="{{ old('email') ?? $user->email}}" placeholder="Почта">
            </f-field>
            <f-field class="grid gap-1">
                <label for="login">Логин</label>
                <input class="input" type="text" name="login" id="login" value="{{ old('login') ?? $user->login }}" placeholder="Логин">
            </f-field>
            <f-field class="grid gap-1">
                <label for="role">Роль</label>
                <select name="role" id="role">
                    <option value="{{ $user->role }}">{{ $user->role }}</option>
                    <option value="null">Убрать права модератора</option>
                </select>
            </f-field>
{{--            FIXME: Подумать нужно ли менять пароль?--}}
{{--            <f-field class="grid gap-1">--}}
{{--                <label for="password">Пароль</label>--}}
{{--                <input class="input" type="password" name="password" id="password" placeholder="Пароль">--}}
{{--            </f-field>--}}
{{--            <f-field class="grid gap-1">--}}
{{--                <label for="password_confirm">Повторите пароль</label>--}}
{{--                <input class="input" type="password" name="password_confirmation" id="password_confirm" placeholder="Повторите пароль">--}}
{{--            </f-field>--}}
            <button class="btn btn-accent">Изменить</button>
        </form>
    </body>
</html>

resources/views/admin_layouts/user/users.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Админ панель - пользователи</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="grid bg-light-accent text-sm sm:text-base">
        <header class="flex flex-col sm:flex-row flex-wrap items-center sm:justify-between gap-4 border-2 bg-white p-4 sm:p-8 shadow-lg">
            <a class="btn btn-accent p-2 flex gap-1" href="{{ route('admin-dashboard') }}">
                @include('layouts.svg.left-arrow')
            </a>
            <article class="grid gap-1.5">
                <h1 class="text-2xl sm:text-4xl">Пользователи</h1>
                <span class="line"></span>
            </article>
            <article>
                <form class="flex gap-2 m-0" action="{{ route('users.index') }}">
                    <input class="input" type="text" name="search" id="search" placeholder="Что ищем?">
                    <button class="btn btn-accent p-2">
                        @include('layouts.svg.search')
                    </button>
                </form>
            </article>
        </header>
        <main class="grid gap-4 p-4 sm:p-8">
            <nav class="flex gap-4">
                <a href="{{ route('users.create') }}" class="inline-block btn btn-accent p-2">
                    @include('layouts.svg.add')
                </a>
                <form class="flex gap-2 m-0" action="{{ route('users.index') }}">
                    <select name="sort" id="sort">
                        <option value="asc">Сотировать по возрастанию</option>
                        <option value="desc">Сотировать по убыванию</option>
                    </select>
                    <button class="btn btn-accent p-2">Применить</button>
                </form>
            </nav>
            <section class="grid gap-2">
                @forelse($users as $user)
                    <article class="grid sm:grid-cols-4 gap-2 p-2 sm:p-4 card">
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">ID</p>
                            <p class="text-base sm:text-xl">{{ $user->id }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">E-mail</p>
                            <p class="text-base sm:text-xl ">{{ $user->email }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">Логин</p>
                            <p class="text-base sm:text-xl ">{{ $user->login }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">Роль</p>
                            <p class="text-base sm:text-xl ">{{ $user->role }}</p>
                        </t-cell>
                        <nav class="col-span-full flex justify-end gap-1">
                            <a class="btn btn-accent p-2" href="{{ route("users.edit", ["user" => $user]) }}">
                                @include('layouts.svg.edit')
                            </a>
                            <form class="m-0 grid" action="{{ route("users.destroy", ["user" => $user]) }}" method="post">
                                @csrf
                                @method("DELETE")
                                <button class="btn btn-red p-2">
                                    @include('layouts.svg.delete')
                                </button>
                            </form>
                        </nav>
                    </article>
                @empty
                    <h2 class="text-2xl">Пусто</h2>
                @endforelse
            </section>
        </main>
    </body>
</html>