routes/web.php
<?php


use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\EventController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\Public\SectionController as PublicSection;
use App\Http\Controllers\Public\ArticleController as PublicArticle;
use App\Http\Controllers\Public\EventController as PublicEvent;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => '/'], function() {
    Route::get('', [MainController::class, 'index'])->name('index');

    Route::get('authorize', [AuthController::class, 'showAuth'])->name('authorize');
    Route::post('authorize', [AuthController::class, 'auth'])->name('authorize.post');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    Route::group(['prefix' => 'section'], function() {
//        FIXME: подумать ещё раз над URL
        Route::get('{sectionAlias}/{subsectionAlias}/articles/{articleAlias}', [PublicArticle::class, 'getSubsectionArticle'])->name('get-subsection-article');
        Route::get('{sectionAlias}/articles/{articleAlias}', [PublicArticle::class, 'getSectionArticle'])->name('get-section-article');
        Route::get('{sectionAlias}/{subsectionAlias}', [PublicSection::class, 'getSubsection'])->name('get-subsection');
        Route::get('{sectionAlias}', [PublicSection::class, 'getSection'])->name('get-section');
    });

    Route::group(['prefix' => 'events'], function() {
        Route::get('today', [PublicEvent::class, 'getTodayEvents'])->name('today-events');
        Route::get('coming-soon', [PublicEvent::class, 'getComingSoonEvents'])->name('coming-son-events');
        Route::get('off-site', [PublicEvent::class, 'getOffsiteEvents'])->name('off-site-events');
    });

    Route::group(['prefix' => 'admin', 'middleware' => 'role'], function() {
        Route::get('', [AdminController::class, 'index'])->name('admin-dashboard');
        Route::resource('users', UserController::class);
        Route::resource('partners', PartnerController::class);
        Route::resource('banners', BannerController::class);
        Route::resource('sections', SectionController::class);
        Route::resource('articles', ArticleController::class);
        Route::resource('events', EventController::class);
        Route::get('images', [ImageController::class, 'getImages'])->name('images');
        Route::post('images/{image}', [ImageController::class, 'deleteImage'])->name('delete-image');
        Route::get('images/{id}/update', [ImageController::class, 'getEditImage'])->name('update-image');
        Route::post('images/{id}/update', [ImageController::class, 'editImage'])->name('update-image-post');
        Route::post('images/store', [ImageController::class, 'store'])->name('images.store');
    });
});

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    use HasFactory;

    public function image() {
        return $this->belongsTo(Image::class);
    }
}

app/Http/Controllers/Admin/BannerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\ImageController;
use App\Http\Requests\Banner\CreateBannerRequestController;
use App\Http\Requests\Banner\UpdateBannerRequestController;
use App\Models\Banner;
use Illuminate\Http\Request;

class BannerController extends Controller
{
    private $sorting;

    public function __construct() {
        $this->sorting = [
            'asc' => ['id', 'asc'],
            'desc' => ['id', 'desc']
        ];
    }

    public function index(Request $request)
    {
        $params = $request->validate([
            'search' => 'sometimes',
            'sort' => 'sometimes'
        ]);

        $banners = Banner::query()->with('image');

        if (isset($params['search']) && !empty($params['search'])) {
            $banners = $banners->where('name', 'like', '%' . $params['search'] . '%');
        }

        if (isset($params['sort']) && !empty($params['sort'])) {
            $currentParams = $this->sorting[$params['sort']];
            $banners = $banners->orderBy($currentParams[0], $currentParams[1]);
        }

        $banners = $banners->get();


        return view('admin_layouts.banner.banners', [
            'banners' => $banners
        ]);
    }

    public function create()
    {
        return view('admin_layouts.banner.create_banner');
    }

    public function store(CreateBannerRequestController $request)
    {
        $post = $request->validated();

        $banner = new Banner();
        $banner->name = $post['name'];
        $banner->link = $post['link'];
        $banner->image_id = ImageController::createImage('banners', $post['image'], $post['alt']);
        $banner->save();

        return redirect()->route('banners.index');
    }

    public function show(Banner $banner)
    {
        $bannerShow = Banner::find($banner->id);

        return view('banner', [
            'banner' => $bannerShow
        ]);
    }

    public function edit(Banner $banner)
    {
        $bannerEdit = Banner::with('image')->findOrFail($banner->id);

        return view('admin_layouts.banner.edit_banner', [
            'banner' => $bannerEdit
        ]);
    }

    public function update(UpdateBannerRequestController $request, Banner $banner)
    {
        $post = $request->validated();

        $updateBanner = Banner::with('image')->find($banner->id);
        if (isset($post['image'])) {
            ImageController::updateImage($updateBanner->image->path, $post['image']);
        }
        $updateBanner->name = $post['name'];
        $updateBanner->link = $post['link'];
        $updateBanner->image()->update([
            'alt' => $post['alt']
        ]);
        $updateBanner->save();

        return redirect()->route('banners.index');
    }

    public function destroy(Banner $banner)
    {
        $deleteBanner = Banner::find($banner->id);
        ImageController::deleteImage($deleteBanner->image);
        $deleteBanner->delete();

        return redirect()->route('banners.index');
    }
}

resources/views/admin_layouts/banner/banner.blade.php
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
        <h1>asdas</h1>
    </body>
</html>

resources/views/admin_layouts/banner/banners.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Админ панель - баннеры</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="grid bg-light-accent text-sm sm:text-base">
        <header class="flex flex-col sm:flex-row flex-wrap items-center sm:justify-between gap-4 border-2 bg-white p-4 sm:p-8 shadow-lg">
            <a class="btn btn-accent p-2 flex gap-1" href="{{ route('admin-dashboard') }}">
                @include('layouts.svg.left-arrow')
            </a>
            <article class="grid gap-1.5">
                <h1 class="text-2xl sm:text-4xl">Баннеры</h1>
                <span class="line"></span>
            </article>
            <article>
                <form class="flex gap-2 m-0" action="{{ route('banners.index') }}">
                    <input class="input" type="text" name="search" id="search" placeholder="Что ищем?">
                    <button class="btn btn-accent p-2">
                        @include('layouts.svg.search')
                    </button>
                </form>
            </article>
        </header>
        <main class="grid gap-4 p-4 sm:p-8">
            <nav class="flex gap-4">
                <a href="{{ route('banners.create') }}" class="inline-block btn btn-accent p-2">
                    @include('layouts.svg.add')
                </a>
                <form class="flex gap-2 m-0" action="{{ route('banners.index') }}">
                    <select name="sort" id="sort">
                        <option value="asc">Сотировать по возрастанию</option>
                        <option value="desc">Сотировать по убыванию</option>
                    </select>
                    <button class="btn btn-accent p-2">Применить</button>
                </form>
            </nav>
            <section class="grid gap-2">
                @forelse($banners as $banner)
                    <article class="grid sm:grid-cols-4 gap-2 p-2 sm:p-4 card">
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">ID</p>
                            <p class="text-base sm:text-xl">{{ $banner->id }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">Имя</p>
                            <p class="text-base sm:text-xl ">{{ $banner->name }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">Ссылка</p>
                            <p class="text-base sm:text-xl">{{ $banner->link }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">ID Изображения</p>
                            <a class="text-base sm:text-xl link" href="{{ route('update-image', ['id' => $banner->image->id]) }}">{{ $banner->image->id }}</a>
                        </t-cell>
                        <nav class="col-span-full flex justify-end gap-1">
                            <a class="btn btn-accent p-2" href="{{ route("banners.edit", ["banner" => $banner]) }}">
                                @include('layouts.svg.edit')
                            </a>
                            <form class="m-0 grid" action="{{ route('banners.destroy', ['banner' => $banner]) }}" method="post">
                                @csrf
                                @method("DELETE")
                                <button class="btn btn-red p-2">
                                    @include('layouts.svg.delete')
                                </button>
                            </form>
                        </nav>
                    </article>
                @empty
                    <h2 class="text-2xl">Пусто</h2>
                @endforelse
            </section>
        </main>
    </body>
</html>

resources/views/admin_layouts/banner/create_banner.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Создание баннера</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="centered-page">
        <form class="centered-form p-4 sm:p-8" action="{{ route('banners.store') }}" method="post" enctype="multipart/form-data">
            <header class="grid gap-2">
                <a class="link flex gap-1" href="{{ route('banners.index') }}">
                    @include('layouts.svg.left-arrow')
                    Назад
                </a>
                <h1 class="text-2xl sm:text-4xl text-center">Создание баннера</h1>
                <span class="line"></span>
            </header>
            @if ($errors->any())
                <div class="bg-red-500 border border-red-600 p-1 rounded text-white">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @csrf
            <f-field class="grid gap-1">
                <label for="name">Название</label>
                <input class="input" type="text" name="name" id="name" value="{{ old('name') }}" placeholder="Название">
            </f-field>
            <f-field class="grid gap-1">
                <label for="link">Ссылка</label>
                <input class="input" type="text" name="link" id="link" value="{{ old('link') }}" placeholder="Ссылка">
            </f-field>
            <f-field class="grid gap-1">
                <label for="alt">Альтернативное название фотографии</label>
                <input class="input" type="text" name="alt" id="alt" value="{{ old('alt') }}" placeholder="Альтернативное название">
            </f-field>
            <f-field class="grid gap-1">
                <label for="image">Фотография</label>
                <input class="input" type="file" name="image" id="image" placeholder="Обложка баннера">
            </f-field>
            <button class="btn btn-accent">Создать</button>
        </form>
    </body>
</html>

resources/views/admin_layouts/banner/edit_banner.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Изменение баннера</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="centered-page">
        <form class="centered-form p-4 sm:p-8" action="{{ route('banners.update', ['banner' => $banner]) }}" method="post" enctype="multipart/form-data">
            <header class="grid gap-2">
                <a class="link flex gap-1" href="{{ route('banners.index') }}">
                    @include('layouts.svg.left-arrow')
                    Назад
                </a>
                <h1 class="text-2xl sm:text-4xl text-center">Изменение баннера</h1>
                <span class="line"></span>
            </header>
            @if ($errors->any())
                <div class="bg-red-500 border border-red-600 p-1 rounded text-white">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @csrf
            @method('PUT')
{{--            TODO: при изменение показывать текущую фотографию--}}
            <f-field class="grid gap-1">
                <label for="name">Название</label>
                <input class="input" type="text" name="name" id="name" value="{{ old('name') ?? $banner->name }}" placeholder="Название">
            </f-field>
            <f-field class="grid gap-1">
                <label for="link">Ссылка</label>
                <input class="input" type="text" name="link" id="link" value="{{ old('link') ?? $banner->link }}" placeholder="Ссылка">
            </f-field>
            <f-field class="grid gap-1">
                <label for="alt">Альтернативное название фотографии</label>
                <input class="input" type="text" name="alt" id="alt" value="{{ old('alt') ?? $banner->image->alt }}" placeholder="Альтернативное название">
            </f-field>
            <f-field class="grid gap-1">
                <label for="image">Фотография</label>
                <input class="input" type="file" name="image" id="image" placeholder="Обложка баннера">
            </f-field>
            <button class="btn btn-accent">Изменить</button>
        </form>
    </body>
</html>