routes/web.php
<?php


use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\EventController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\Public\SectionController as PublicSection;
use App\Http\Controllers\Public\ArticleController as PublicArticle;
use App\Http\Controllers\Public\EventController as PublicEvent;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => '/'], function() {
    Route::get('', [MainController::class, 'index'])->name('index');

    Route::get('authorize', [AuthController::class, 'showAuth'])->name('authorize');
    Route::post('authorize', [AuthController::class, 'auth'])->name('authorize.post');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    Route::group(['prefix' => 'section'], function() {
//        FIXME: подумать ещё раз над URL
        Route::get('{sectionAlias}/{subsectionAlias}/articles/{articleAlias}', [PublicArticle::class, 'getSubsectionArticle'])->name('get-subsection-article');
        Route::get('{sectionAlias}/articles/{articleAlias}', [PublicArticle::class, 'getSectionArticle'])->name('get-section-article');
        Route::get('{sectionAlias}/{subsectionAlias}', [PublicSection::class, 'getSubsection'])->name('get-subsection');
        Route::get('{sectionAlias}', [PublicSection::class, 'getSection'])->name('get-section');
    });

    Route::group(['prefix' => 'events'], function() {
        Route::get('today', [PublicEvent::class, 'getTodayEvents'])->name('today-events');
        Route::get('coming-soon', [PublicEvent::class, 'getComingSoonEvents'])->name('coming-son-events');
        Route::get('off-site', [PublicEvent::class, 'getOffsiteEvents'])->name('off-site-events');
    });

    Route::group(['prefix' => 'admin', 'middleware' => 'role'], function() {
        Route::get('', [AdminController::class, 'index'])->name('admin-dashboard');
        Route::resource('users', UserController::class);
        Route::resource('partners', PartnerController::class);
        Route::resource('banners', BannerController::class);
        Route::resource('sections', SectionController::class);
        Route::resource('articles', ArticleController::class);
        Route::resource('events', EventController::class);
        Route::get('images', [ImageController::class, 'getImages'])->name('images');
        Route::post('images/{image}', [ImageController::class, 'deleteImage'])->name('delete-image');
        Route::get('images/{id}/update', [ImageController::class, 'getEditImage'])->name('update-image');
        Route::post('images/{id}/update', [ImageController::class, 'editImage'])->name('update-image-post');
        Route::post('images/store', [ImageController::class, 'store'])->name('images.store');
    });
});

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Section extends Model
{
    use HasFactory;

    public function articles() {
        return $this->hasMany(Article::class);
    }

    public function image() {
        return $this->belongsTo(Image::class);
    }

    public function parent() {
        return $this->belongsTo(Section::class, 'parent_id');
    }

    public function children() {
        return $this->hasMany(Section::class, 'parent_id');
    }
}

app/Http/Controllers/Admin/SectionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\ImageController;
use App\Http\Requests\Section\CreateSectionRequestController;
use App\Http\Requests\Section\UpdateSectionRequestController;
use App\Models\Section;
use Illuminate\Http\Request;

class SectionController extends Controller
{
    private $sorting;

    public function __construct() {
        $this->sorting = [
            'asc' => ['id', 'asc'],
            'desc' => ['id', 'desc']
        ];
    }

    public function index(Request $request)
    {
        $params = $request->validate([
            'search' => 'sometimes',
            'sort' => 'sometimes'
        ]);

        $sections = Section::query()->with([
            'image',
            'parent'
        ]);

        if (isset($params['search']) && !empty($params['search'])) {
            $sections = $sections->whereRaw("MATCH(title,description) AGAINST(? IN BOOLEAN MODE)", [$params['search']]);
        }

        if (isset($params['sort']) && !empty($params['sort'])) {
            $currentParams = $this->sorting[$params['sort']];
            $sections = $sections->orderBy($currentParams[0], $currentParams[1]);
        }

        $sections = $sections->get();

        return view('admin_layouts.section.sections', [
            'sections' => $sections
        ]);
    }

    public function create()
    {
        $sections = Section::whereNull('parent_id')->get();

        return view('admin_layouts.section.create_section', [
            'sections' => $sections
        ]);
    }

    public function store(CreateSectionRequestController $request)
    {
        $post = $request->validated();

        $section = new Section();
        $section->title = $post['title'];
        $section->description = $post['description'];
        $section->parent_id = $post['parent_id'] == "null" ? null : $post['parent_id'];
        $section->alias = $post['alias'];
        $section->image_id = ImageController::createImage('sections', $post['image'], $post['alt']);
        $section->save();

        return redirect()->route('sections.index');
    }

    public function edit(Section $section)
    {
        $sections = Section::whereNull('parent_id')->get();
        $editSection = Section::find($section->id);

        return view('admin_layouts.section.edit_section', [
            'section' => $editSection,
            'sections' => $sections
        ]);
    }

    public function update(UpdateSectionRequestController $request, Section $section)
    {
        $post = $request->validated();

        $updateSection = Section::with('image')->find($section->id);

        if (isset($post['image'])) {
            ImageController::updateImage($updateSection->image->path, $post['image']);
        }

        $updateSection->title = $post['title'];
        $updateSection->description = $post['description'];
        $updateSection->parent_id = $post['parent_id'] == "null" ? null : $post['parent_id'];
        $updateSection->alias = $post['alias'];
        $updateSection->image()->update([
            'alt' => $post['alt']
        ]);
        $updateSection->save();

        return redirect()->route('sections.index');
    }

    public function destroy(Section $section)
    {
        $deleteSection = Section::find($section->id);
        ImageController::deleteImage($deleteSection->image);
        $deleteSection->delete();

        return redirect()->route('sections.index');
    }
}

app/Http/Controllers/Public/SectionController.php
<?php

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use App\Models\Section;
use Illuminate\Http\Request;

class SectionController extends Controller
{
    public function getSection($alias)
    {
        $section = Section::with([
            'image',
            'articles',
            'children'
        ])
            ->where('alias', $alias)
            ->first();

        return view('public.section', [
            'section' => $section
        ]);
    }

    public function getSubsection($sectionAlias, $subsectionAlias)
    {
        $subsection = Section::with([
            'image',
            'articles'
        ])
            ->where('alias', $subsectionAlias)
            ->first();

        return view('public.subsection', [
            'subsection' => $subsection,
            'sectionAlias' => $sectionAlias
        ]);
    }
}

resources/views/admin_layouts/section/create_section.blade.php
 <html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
     <head>
         <meta charset="UTF-8">
         <meta name="viewport"
               content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
         <meta http-equiv="X-UA-Compatible" content="ie=edge">
         <title>Создание секции</title>
         <link href="{{ asset('css/app.css') }}" rel="stylesheet">
     </head>
     <body class="centered-page">
         <form class="centered-form p-4 sm:p-8" action="{{ route('sections.store') }}" method="post" enctype="multipart/form-data">
             <header class="grid gap-2">
                 <a class="link flex gap-1" href="{{ route('sections.index') }}">
                     @include('layouts.svg.left-arrow')
                     Назад
                 </a>
                 <h1 class="text-2xl sm:text-4xl text-center">Создание секции</h1>
                 <span class="line"></span>
             </header>
             @if ($errors->any())
                 <div class="bg-red-500 border border-red-600 p-1 rounded text-white">
                     <ul>
                         @foreach ($errors->all() as $error)
                             <li>{{ $error }}</li>
                         @endforeach
                     </ul>
                 </div>
             @endif
             @csrf
             <f-field class="grid gap-1">
                 <label for="title">Название секции</label>
                 <input class="input" type="text" name="title" id="title" value="{{ old('title') }}" placeholder="Название секции">
             </f-field>
             <f-field class="grid gap-1">
                 <label for="alias">Псевдоним</label>
                 <input class="input" type="text" name="alias" id="alias" value="{{ old('alias') }}" placeholder="Псевдоним">
             </f-field>
             <f-field class="grid gap-1">
                 <label for="parent_id">Родительская секция</label>
                 <select name="parent_id" id="parent_id">
                     <option value="null">Выберите родительскую секцию</option>
                     @foreach($sections as $section)
                         <option value="{{ $section->id }}">{{ $section->title }}</option>
                     @endforeach
                 </select>
             </f-field>
             <f-field class="grid gap-1">
                 <label for="alt">Альтернативное название фотографии</label>
                 <input class="input" type="text" name="alt" id="alt" value="{{ old('alt') }}" placeholder="Альтернативное название">
             </f-field>
             <f-field class="grid gap-1">
                 <label for="image">Фотография</label>
                 <input class="input" type="file" name="image" id="image" placeholder="Обложка баннера">
             </f-field>
             <f-field class="grid gap-1">
                 <label for="description">Описание секции</label>
                 <textarea class="input" name="description" cols="30" rows="10">{{ old('description') }}</textarea>
             </f-field>
             <button class="btn btn-accent">Создать</button>
         </form>
     </body>
 </html>

resources/views/admin_layouts/section/edit_section.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Изменение секции</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="centered-page">
        <form class="centered-form p-4 sm:p-8" action="{{ route('sections.update', ['section' => $section]) }}" method="post" enctype="multipart/form-data">
            <header class="grid gap-2">
                <a class="link flex gap-1" href="{{ route('sections.index') }}">
                    @include('layouts.svg.left-arrow')
                    Назад
                </a>
                <h1 class="text-2xl sm:text-4xl text-center">Изменение секции</h1>
                <span class="line"></span>
            </header>
            @if ($errors->any())
                <div class="bg-red-500 border border-red-600 p-1 rounded text-white">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @csrf
            @method('PUT')
            <f-field class="grid gap-1">
                <label for="title">Название секции</label>
                <input class="input" type="text" name="title" id="title" value="{{ old('title') ?? $section->title }}" placeholder="Название секции">
            </f-field>
            <f-field class="grid gap-1">
                <label for="parent_id">Родительская секция</label>
                <select name="parent_id" id="parent_id">
                    <option value="null">Выберите родительскую секцию</option>
                    <option value="null">Убрать из родительской секции</option>
                    @foreach($sections as $section)
                        <option value="{{ $section->id }}">{{ $section->title }}</option>
                    @endforeach
                </select>
            </f-field>
            <f-field class="grid gap-1">
                <label for="alt">Альтернативное название фотографии</label>
                <input class="input" type="text" name="alt" id="alt" value="{{ old('alt') ?? $section->image->alt }}" placeholder="Альтернативное название">
            </f-field>
            <f-field class="grid gap-1">
                <label for="image">Фотография</label>
                <input class="input" type="file" name="image" id="image" placeholder="Обложка секции">
            </f-field>
            <f-field class="grid gap-1">
                <label for="description">Описание секции</label>
                <textarea class="input" name="description" cols="30" rows="10">{{ old('description') ?? $section->description }}</textarea>
            </f-field>
            <button class="btn btn-accent">Изменить</button>
        </form>
    </body>
</html>

resources/views/admin_layouts/section/sections.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Админ панель - секции</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="grid bg-light-accent text-sm sm:text-base">
        <header class="flex flex-col sm:flex-row flex-wrap items-center sm:justify-between gap-4 border-2 bg-white p-4 sm:p-8 shadow-lg">
            <a class="btn btn-accent p-2 flex gap-1" href="{{ route('admin-dashboard') }}">
                @include('layouts.svg.left-arrow')
            </a>
            <article class="grid gap-1.5">
                <h1 class="text-2xl sm:text-4xl">Секции</h1>
                <span class="line"></span>
            </article>
            <article>
                <form class="flex gap-2 m-0" action="{{ route('sections.index') }}">
                    <input class="input" type="text" name="search" id="search" placeholder="Что ищем?">
                    <button class="btn btn-accent p-2">
                        @include('layouts.svg.search')
                    </button>
                </form>
            </article>
        </header>
        <main class="grid gap-4 p-4 sm:p-8">
            <nav class="flex gap-4">
                <a href="{{ route('sections.create') }}" class="inline-block btn btn-accent p-2">
                    @include('layouts.svg.add')
                </a>
                <form class="flex gap-2 m-0" action="{{ route('sections.index') }}">
                    <select name="sort" id="sort">
                        <option value="asc">Сотировать по возрастанию</option>
                        <option value="desc">Сотировать по убыванию</option>
                    </select>
                    <button class="btn btn-accent p-2">Применить</button>
                </form>
            </nav>
            <section class="grid gap-2">
                @forelse($sections as $section)
                    <article class="grid sm:grid-cols-4 gap-2 p-2 sm:p-4 card">
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">ID</p>
                            <p class="text-base sm:text-xl">{{ $section->id }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">Название секции</p>
                            <p class="text-base sm:text-xl ">{{ $section->title }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">Псевдоним</p>
                            <p class="text-base sm:text-xl ">{{ $section->alias }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">ID фотографии</p>
                            <a class="text-base sm:text-xl link" href="{{ route('update-image', ['id' => $section->image->id]) }}">{{ $section->image->id }}</a>
                        </t-cell>
                        @if($section->parent)
                            <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                                <p class="text-gray-500">Родительская секция</p>
                                <p class="text-base sm:text-xl ">{{ $section->parent->title }}</p>
                            </t-cell>
                        @endif
                        <nav class="col-span-full flex justify-end gap-1">
                            <a class="btn btn-accent p-2" href="{{ route("sections.edit", ["section" => $section]) }}">
                                @include('layouts.svg.edit')
                            </a>
                            <form class="m-0 grid" action="{{ route("sections.destroy", ["section" => $section]) }}" method="post">
                                @csrf
                                @method("DELETE")
                                <button class="btn btn-red p-2">
                                    @include('layouts.svg.delete')
                                </button>
                            </form>
                        </nav>
                    </article>
                @empty
                    <h2 class="text-2xl">Пусто</h2>
                @endforelse
            </section>
        </main>
    </body>
</html>