routes/web.php
<?php


use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\EventController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\Public\SectionController as PublicSection;
use App\Http\Controllers\Public\ArticleController as PublicArticle;
use App\Http\Controllers\Public\EventController as PublicEvent;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => '/'], function() {
    Route::get('', [MainController::class, 'index'])->name('index');

    Route::get('authorize', [AuthController::class, 'showAuth'])->name('authorize');
    Route::post('authorize', [AuthController::class, 'auth'])->name('authorize.post');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    Route::group(['prefix' => 'section'], function() {
//        FIXME: подумать ещё раз над URL
        Route::get('{sectionAlias}/{subsectionAlias}/articles/{articleAlias}', [PublicArticle::class, 'getSubsectionArticle'])->name('get-subsection-article');
        Route::get('{sectionAlias}/articles/{articleAlias}', [PublicArticle::class, 'getSectionArticle'])->name('get-section-article');
        Route::get('{sectionAlias}/{subsectionAlias}', [PublicSection::class, 'getSubsection'])->name('get-subsection');
        Route::get('{sectionAlias}', [PublicSection::class, 'getSection'])->name('get-section');
    });

    Route::group(['prefix' => 'events'], function() {
        Route::get('today', [PublicEvent::class, 'getTodayEvents'])->name('today-events');
        Route::get('coming-soon', [PublicEvent::class, 'getComingSoonEvents'])->name('coming-son-events');
        Route::get('off-site', [PublicEvent::class, 'getOffsiteEvents'])->name('off-site-events');
    });

    Route::group(['prefix' => 'admin', 'middleware' => 'role'], function() {
        Route::get('', [AdminController::class, 'index'])->name('admin-dashboard');
        Route::resource('users', UserController::class);
        Route::resource('partners', PartnerController::class);
        Route::resource('banners', BannerController::class);
        Route::resource('sections', SectionController::class);
        Route::resource('articles', ArticleController::class);
        Route::resource('events', EventController::class);
        Route::get('images', [ImageController::class, 'getImages'])->name('images');
        Route::post('images/{image}', [ImageController::class, 'deleteImage'])->name('delete-image');
        Route::get('images/{id}/update', [ImageController::class, 'getEditImage'])->name('update-image');
        Route::post('images/{id}/update', [ImageController::class, 'editImage'])->name('update-image-post');
        Route::post('images/store', [ImageController::class, 'store'])->name('images.store');
    });
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    public function section() {
        return $this->belongsTo(Section::class);
    }

    public function image() {
        return $this->belongsTo(Image::class);
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\ImageController;
use App\Http\Requests\Article\CreateArticleRequestController;
use App\Http\Requests\Article\UpdateArticleRequestController;
use App\Models\Article;
use App\Models\Section;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    private $sorting;

    public function __construct() {
        $this->sorting = [
            'asc' => ['id', 'asc'],
            'desc' => ['id', 'desc']
        ];
    }

    public function index(Request $request)
    {
        $params = $request->validate([
            'search' => 'sometimes',
            'sort' => 'sometimes'
        ]);

        $articles = Article::query()->with([
            'image',
            'section'
        ]);

        if (isset($params['search']) && !empty($params['search'])) {
            $articles = $articles->whereRaw("MATCH(title,description,annotation) AGAINST(? IN BOOLEAN MODE)", [$params['search']]);
        }

        if (isset($params['sort']) && !empty($params['sort'])) {
            $currentParams = $this->sorting[$params['sort']];
            $articles = $articles->orderBy($currentParams[0], $currentParams[1]);
        }

        $articles = $articles->get();

        return view('admin_layouts.article.articles', [
            'articles' => $articles,
        ]);
    }

    public function create()
    {
        $sections = Section::query()->get();

        return view('admin_layouts.article.create_article', [
            'sections' => $sections
        ]);
    }

    public function store(CreateArticleRequestController $request)
    {
        $post = $request->validated();

        $article = new Article();
        $article->title = $post['title'];
        $article->description = $post['description'];
        $article->annotation = $post['annotation'];
        $article->image_id = ImageController::createImage('articles', $post['image'], $post['alt']);
        $article->section_id = $post['section'];
        $article->alias = $post['alias'];
        $article->save();

        return redirect()->route('articles.index');
    }

    public function show(Article $article)
    {
        //
    }

    public function edit(Article $article)
    {
        $editArticle = Article::with([
            'image',
            'section'
        ])->find($article->id);

        $sections = Section::query()->get();

        return view('admin_layouts.article.edit_article', [
            'article' => $editArticle,
            'sections' => $sections
        ]);
    }

    public function update(UpdateArticleRequestController $request, Article $article)
    {
        $post = $request->validated();

        $updateArticle = Article::with('image')->find($article->id);

        if (isset($post['image'])) {
            ImageController::updateImage($updateArticle->image->path, $post['image']);
        }

        $updateArticle->title = $post['title'];
        $updateArticle->description = $post['description'];
        $updateArticle->annotation = $post['annotation'];
        $updateArticle->section_id = $post['section'];
        $updateArticle->alias = $post['alias'];
        $updateArticle->image()->update([
            'alt' => $post['alt']
        ]);
        $updateArticle->save();

        return redirect()->route('articles.index');
    }

    public function destroy(Article $article)
    {
        $deleteArticle = Article::find($article->id);
        ImageController::deleteImage($deleteArticle->image);
        $deleteArticle->delete();

        return redirect()->route('articles.index');
    }
}

app/Http/Controllers/Public/ArticleController.php
<?php

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use App\Models\Article;

class ArticleController extends Controller
{
    public function getSectionArticle($sectionAlias, $articleAlias) {
        $article = Article::with([
            'image',
            'section'
        ])
            ->where('alias', $articleAlias)
            ->first();

        return view('public.article', [
            'article' => $article
        ]);
    }

    public function getSubsectionArticle($sectionAlias, $subsectionAlias, $articleAlias) {
        $article = Article::with([
            'image',
            'section'
        ])
            ->where('alias', $articleAlias)
            ->first();

        return view('public.article', [
            'article' => $article
        ]);
    }
}

resources/views/admin_layouts/article/articles.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Админ панель - статьи</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="grid bg-light-accent text-sm sm:text-base">
        <header class="flex flex-col sm:flex-row flex-wrap items-center sm:justify-between gap-4 border-2 bg-white p-4 sm:p-8 shadow-lg">
            <a class="btn btn-accent p-2 flex gap-1" href="{{ route('admin-dashboard') }}">
                @include('layouts.svg.left-arrow')
            </a>
            <article class="grid gap-1.5">
                <h1 class="text-2xl sm:text-4xl">Статьи</h1>
                <span class="line"></span>
            </article>
            <article>
                <form class="flex gap-2 m-0" action="{{ route('articles.index') }}">
                    <input class="input" type="text" name="search" id="search" placeholder="Что ищем?">
                    <button class="btn btn-accent p-2">
                        @include('layouts.svg.search')
                    </button>
                </form>
            </article>
        </header>
        <main class="grid gap-4 p-4 sm:p-8">
            <nav class="flex gap-4">
                <a href="{{ route('articles.create') }}" class="inline-block btn btn-accent p-2">
                    @include('layouts.svg.add')
                </a>
                <form class="flex gap-2 m-0" action="{{ route('articles.index') }}">
                    <select name="sort" id="sort">
                        <option value="asc">Сотировать по возрастанию</option>
                        <option value="desc">Сотировать по убыванию</option>
                    </select>
                    <button class="btn btn-accent p-2">Применить</button>
                </form>
            </nav>
            <section class="grid gap-2">
                @forelse($articles as $article)
                    <article class="grid sm:grid-cols-5 gap-2 p-2 sm:p-4 card">
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">ID</p>
                            <p class="text-base sm:text-xl">{{ $article->id }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">Название статьи</p>
                            <p class="text-base sm:text-xl ">{{ $article->title }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">Псевдоним</p>
                            <p class="text-base sm:text-xl ">{{ $article->alias }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">К какой секции принадлежит</p>
                            <p class="text-base sm:text-xl ">{{ $article->section->title }}</p>
                        </t-cell>
                        <t-cell class="bg-gray-100 p-1 rounded border-2 hover:shadow-inner">
                            <p class="text-gray-500">ID фотографии</p>
                            <a class="text-base sm:text-xl link" href="{{ route('update-image', ['id' => $article->image->id]) }}">{{ $article->image->id }}</a>
                        </t-cell>
                        <nav class="col-span-full flex justify-end gap-1">
                            <a class="btn btn-accent p-2" href="{{ route("articles.edit", ["article" => $article]) }}">
                                @include('layouts.svg.edit')
                            </a>
                            <form class="m-0 grid" action="{{ route("articles.destroy", ["article" => $article]) }}" method="post">
                                @csrf
                                @method("DELETE")
                                <button class="btn btn-red p-2">
                                    @include('layouts.svg.delete')
                                </button>
                            </form>
                        </nav>
                    </article>
                @empty
                    <h2 class="text-2xl">Пусто</h2>
                @endforelse
            </section>
        </main>
    </body>
</html>

resources/views/admin_layouts/article/create_article.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Создание статьи</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="centered-page">
        <form class="centered-form p-4 sm:p-8" action="{{ route('articles.store') }}" method="post" enctype="multipart/form-data">
            <header class="grid gap-2">
                <a class="link flex gap-1" href="{{ route('articles.index') }}">
                    @include('layouts.svg.left-arrow')
                    Назад
                </a>
                <h1 class="text-2xl sm:text-4xl text-center">Создание статьи</h1>
                <span class="line"></span>
            </header>
            @if ($errors->any())
                <div class="bg-red-500 border border-red-600 p-1 rounded text-white">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @csrf
            <f-field class="grid gap-1">
                <label for="title">Название статьи</label>
                <input class="input" type="text" name="title" id="title" value="{{ old('title') }}" placeholder="Название статьи">
            </f-field>
            <f-field class="grid gap-1">
                <label for="alias">Псевдоним</label>
                <input class="input" type="text" name="alias" id="alias" value="{{ old('alias') }}" placeholder="Псевдоним">
            </f-field>
            <f-field class="grid gap-1">
                <label for="section">Секция</label>
                <select name="section" id="section">
                    <option value="" selected disabled>Выберите секцию</option>
                    @foreach($sections as $section)
                        <option value="{{ $section->id }}">{{ $section->title }}</option>
                    @endforeach
                </select>
            </f-field>
            <f-field class="grid gap-1">
                <label for="alt">Альтернативное название фотографии</label>
                <input class="input" type="text" name="alt" id="alt" value="{{ old('alt') }}" placeholder="Альтернативное название">
            </f-field>
            <f-field class="grid gap-1">
                <label for="image">Фотография</label>
                <input class="input" type="file" name="image" id="image" placeholder="Обложка статьи">
            </f-field>
            <f-field class="grid gap-1">
                <label for="annotation">Аннотация</label>
                <textarea class="input" name="annotation" cols="30" rows="10" id="annotation">{{ old('annotation') }}</textarea>
            </f-field>
            <f-field class="grid gap-1">
                <label for="description">Описание</label>
                <textarea name="description" cols="30" rows="10" id="textarea">{{ old('description') }}</textarea>
            </f-field>
            <button class="btn btn-accent">Создать</button>
        </form>
        @include('components.ckeditor')
    </body>
</html>

resources/views/admin_layouts/article/edit_article.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Изменение статьи</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="centered-page">
        <form class="centered-form p-4 sm:p-8" action="{{ route('articles.update', ['article' => $article]) }}" method="post" enctype="multipart/form-data">
            <header class="grid gap-2">
                <a class="link flex gap-1" href="{{ route('articles.index') }}">
                    @include('layouts.svg.left-arrow')
                    Назад
                </a>
                <h1 class="text-2xl sm:text-4xl text-center">Изменение статьи</h1>
                <span class="line"></span>
            </header>
            @if ($errors->any())
                <div class="bg-red-500 border border-red-600 p-1 rounded text-white">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @csrf
            @method('PUT')
            <f-field class="grid gap-1">
                <label for="title">Название статьи</label>
                <input class="input" type="text" name="title" id="title" value="{{ old('title') ?? $article->title }}" placeholder="Название статьи">
            </f-field>
            <f-field class="grid gap-1">
                <label for="alias">Псевдоним</label>
                <input class="input" type="text" name="alias" id="alias" value="{{ old('alias') ?? $article->alias }}" placeholder="Псевдоним">
            </f-field>
            <f-field class="grid gap-1">
                <label for="section">Секция</label>
                <select name="section" id="section">
                    @foreach($sections as $section)
                        <option value="{{ $section->id }}" selected="{{ $article->section_id === $section->id ? "selected" : "" }}">{{ $section->title }}</option>
                    @endforeach
                </select>
            </f-field>
            <f-field class="grid gap-1">
                <label for="alt">Альтернативное название фотографии</label>
                <input class="input" type="text" name="alt" id="alt" value="{{ old('alt') ?? $article->image->alt }}" placeholder="Альтернативное название">
            </f-field>
            <f-field class="grid gap-1">
                <label for="image">Фотография</label>
                <input class="input" type="file" name="image" id="image" placeholder="Обложка статьи">
            </f-field>
            <f-field class="grid gap-1">
                <label for="annotation">Аннотация</label>
                <textarea class="input" name="annotation" cols="30" rows="10">{{ old('annotation') ?? $article->annotation }}</textarea>
            </f-field>
            <f-field class="grid gap-1">
                <label for="description">Описание</label>
                <textarea name="description" cols="30" rows="10" id="textarea">{!! old('description') ?? $article->description !!}</textarea>
            </f-field>
            <button class="btn btn-accent">Изменить</button>
        </form>
        @include('components.ckeditor')
    </body>
</html>